### PR TITLE
updated solution to P02

### PR DESCRIPTION
**Pull request by grd888**
Hi @eneko , I updated my solution to P02 to handle the case of single element List.

### CODE REVIEW

**Comment by eneko** [comment]
Thanks! Just ran the tests again and it seems to fail on a two-element list (works otherwise).
```
[PASS] testP02() 'long list' passed (0.000 seconds) ✔
[FAIL] testP02() 'two element list' failed: nil != 1 (0.000 seconds) ⅹ
[PASS] testP02() 'one element list' passed (0.000 seconds) ✔
```

Hoping to have the test runner ready for everyone to use pretty soon!

**Comment by grd888** [comment]
Darn it. I guess i didn't test it well enough. I'll look into it again later.

Test runner should be great, thanks!

**Comment by grd888** [comment]
I have updated my solution.

**Comment by eneko** [comment]
Woot! All tests passing now. Keep the solutions coming! 

```
$ swift run test grd888
Running tests for: grd888
Compile Swift Module 'grd888' (7 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/grd888
[PASS] testP01() 'last of multiple elements' passed (0.001 seconds) ✔
[PASS] testP01() 'last of one element' passed (0.000 seconds) ✔
[PASS] testP02() 'long list' passed (0.000 seconds) ✔
[PASS] testP02() 'two element list' passed (0.000 seconds) ✔
[PASS] testP02() 'one element list' passed (0.000 seconds) ✔
[PASS] testP03() 'Long middle' passed (0.000 seconds) ✔
[PASS] testP03() 'Long first' passed (0.000 seconds) ✔
[PASS] testP03() 'Out of bounds' passed (0.000 seconds) ✔
[PASS] testP03() 'Single element out of bounds' passed (0.000 seconds) ✔

  ✔ OK > executed 9 tests, with 0 failures in 0.001 seconds
```

PS: I've pushed a still in-progress test runner to `feature/cli` branch. Feel free to check it out to test your solutions with the above command. If you do, let me know how it goes!

**Pull request merged**
