### PR TITLE
p01–p05

### PR DESCRIPTION
**Pull request by tehpsy**
p01–p04 are fairly straightforward recursive solutions, but I'm struggling to find a recursive solution to p05. I used an `Array` in p05, but not `Array.reverse()`.

### CODE REVIEW

**Review by eneko — COMMENTED** [review]
Hi @tehpsy, good start. I’ll give you a hint: try making `reversedValues` a `List` instead of an array. You are very close!

**Comment by tehpsy** [comment]
Thanks @eneko! I'm making progress I think. My work on p07 has helped me understand p05 a bit more. `reverse() -> Void` seems to be quite a bit more challenging than `reversed() -> List`!

**Comment by eneko** [comment]
Please follow the new [setup instructions](https://github.com/eneko/Ninety-Nine-Swift-Solutions/blob/master/README.md) and move your solutions to the `Solutions` folder.

At that point you should be able to run `swift run test tehpsy` to test your solutions.

Regards,
Eneko

**Comment by tehpsy** [comment]
Thanks @eneko, I'm following the new instructions but I've got some errors to fix related to `reverse()`: the problem definition of p05 is `reverse() -> Void`, but I noticed your solution is `reverse() -> List`. Just FYI -- you might want to update the site!

**Comment by tehpsy** [comment]
Hey @eneko, I've updated p05 now! I think some of the other problems also need a tweak on the site (e.g. `func compress() {` instead of `func compress() -> List {`). Also, using your new xcodeproj is there a way to debug?

**Comment by eneko** [comment]
Woot! Super happy to see tests passing on Travis CI. Congrats!

Good catch on `compress()`. You are right, all `List` methods should return a new list. From the instructions:

> Consider instances of List as immutable. All methods should return new instances of linked lists (instead of modifying the current list).

I'll try to update the problem tonight. Thanks!

For debugging, once you open the project in Xcode, select your test target "tehpsy" and hit Run. You should be able to put breakpoints in your code, and also see the output on the console log. Let me know if that is not the case.

**Comment by tehpsy** [comment]
Hmmm... I don't have 'tehpsy' target, but I do have 'test' target (this builds and runs, but says "Could not find any tests to run")...

**Comment by eneko** [comment]
Ok, try running `swift run test tehpsy` and then `swift package generate-xcodeproj`. That should do it.

My goal is to have this process automated on during setup :)

**Comment by tehpsy** [comment]
Thanks @eneko, generating the new xcodeproj seemed to fix it! I added a couple of files manually afterwards and had to add them to Xcode project Sources and then set their target membership to tehpsy (I guess others will have to do a similar thing too).

**Comment by eneko** [comment]
Awesome, thanks! In the future, the command `swift run solve pXX` should take care of that, but I haven't done it yet 😬

**Pull request merged**
